### ISSUE TITLE
How does this compare with https://github.com/divideconcept/FluidLite?

### ISSUE THREAD

**Issue by paulsapps** [dotfloat/fluidsynth-lite#1]
Both seem very similar projects, I too was going to create a "platform abstraction" for fluid synth so external deps could be more easily replaced.

I was wondering do both projects have the same goal?

**Comment by dotfloat** [comment]
Seems like our goals are similar, but not identical. I need SF2 and MIDI support with zero additional dependencies. The only development that's going to happen on this repo is bug fixes.

**Comment by paulsapps** [comment]
Will the bug fixes be syncs from the source forge main fluid synth repo?

**Comment by dotfloat** [comment]
Hopefully. I don't actively watch the sourceforge repo, but I reckon I'll check it once in a while.
